spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/local_db
    username: local_user
    password: local_password
  flyway:
    clean-disabled: false
    baseline-on-migrate: true

feature:
  migrations: true